### ISSUE TITLE
Getting Raw Query

### ISSUE THREAD

**Issue by karthikv29** [pdphilip/laravel-opensearch#2]
Hello @pdphilip ,
Is there a way to log the raw query sent to OpenSearch? The ToSQL() outputs the sql version of the query passed, is there a way to output the OpenSearch query that has been passed to the cluster

**Comment by pdphilip** [comment]
Hey @karthikv29, I'll add this in the next release 👍

**Comment by pdphilip** [comment]
Hi @karthikv29 , if you update to the latest release (v2.0.2) then you'll gave the `toDsl()/toSql()` method available to you.

Docs: https://opensearch.pdphilip.com/os-specific#to-dsl

All the best

**Comment by karthikv29** [comment]
Thanks a lot
